baseURL = "https://zealous-poitras-3f9296.netlify.app/"
languageCode = "en-us"
title = "Jamstack/HTML Boilerplate on Hugo"
disableKinds = ["taxonomy", "taxonomyTerm"]
[outputs]
	home = ["html", "amp"]
	page = ["html", "amp"]
