baseURL = "https://zealous-poitras-3f9296.netlify.app/"
languageCode = "en-us"
title = "Jamstack/HTML Boilerplate on Hugo"
# theme = "ananke"
disableKinds = ["taxonomy", "taxonomyTerm"]
[outputs]
	home = ["html"]
	# home = ["html", "amp", "rss", "json"]
	# page = ["html", "amp"]
